before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: qkW7QeneUZ5VjjAGxCDu61ZU+s/wUjiZTgB5kuV6B3/l/eE84KgsGaoH9m6Vhlolgn61NXDgjFkQhS8Ww7AianGkD+IHXBSDSSUU0wg2q4jdvlDNibcIjObYGTlXTyfPe8gp/Tht2nychXxnq22ZPet//2aitqIB3tCfSk2nT0w+Z+lj2ww9/tqByAmeVMiNymdQ0CI8b/tcOPhFZISSAMaYbPfzT5uDjL8ht6ElxXm5Azuydfz7vE/PXJzpbRW/HKJQOgQhedYDxsZRk5TUQxVPSOgv+e9HAQPinyWGArYz+lTIvh0nIhXT2dGCxr+ooBi2LfqtQdtVSa3e29KjlM6ByWTFPM2FpD9k8qmdort/GvgVAj9g6ZIDbBz29jBu3G/VJPaPZAMK0l+iDqbytIpa/g8khj+RsCTOtSa1V3tThswqpgwznbXKacIjeIn1P7oH9GzD7PNUpfZBSkMgHoL4h5Ev3sZ4AN1NsG8bSDFZ9P5J3ATXybeQpg2V0h8lFDf/OcuUWVPpfPF87StcsWDN5LDX0HuHt6tBlNYjsVU/4oZBmncBq67CRQYPZ2I65YRoFyIxukhuL8oeTpNs287U+Nhs9ssb8N2l+zeEzCzgMjrC1QEwRe5tZcNtUqAMWHkAdwJkUXwjY0PKJtjmtj3XmMNU0NPiNUVBC6ihdiQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
